// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NodeDiscoverer is an autogenerated mock type for the NodeDiscoverer type
type NodeDiscoverer struct {
	mock.Mock
}

type mockConstructorTestingTNewNodeDiscoverer interface {
	mock.TestingT
	Cleanup(func())
}

// NewNodeDiscoverer creates a new instance of NodeDiscoverer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNodeDiscoverer(t mockConstructorTestingTNewNodeDiscoverer) *NodeDiscoverer {
	mock := &NodeDiscoverer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
