// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/kamkalis/object-storage/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NodeDiscoverer is an autogenerated mock type for the NodeDiscoverer type
type NodeDiscoverer struct {
	mock.Mock
}

// DiscoverNodes provides a mock function with given fields: ctx
func (_m *NodeDiscoverer) DiscoverNodes(ctx context.Context) ([]domain.StorageNode, error) {
	ret := _m.Called(ctx)

	var r0 []domain.StorageNode
	if rf, ok := ret.Get(0).(func(context.Context) []domain.StorageNode); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StorageNode)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewNodeDiscoverer interface {
	mock.TestingT
	Cleanup(func())
}

// NewNodeDiscoverer creates a new instance of NodeDiscoverer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNodeDiscoverer(t mockConstructorTestingTNewNodeDiscoverer) *NodeDiscoverer {
	mock := &NodeDiscoverer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
