// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StorageServer is an autogenerated mock type for the StorageServer type
type StorageServer struct {
	mock.Mock
}

type mockConstructorTestingTNewStorageServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewStorageServer creates a new instance of StorageServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStorageServer(t mockConstructorTestingTNewStorageServer) *StorageServer {
	mock := &StorageServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
