// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StorageService is an autogenerated mock type for the StorageService type
type StorageService struct {
	mock.Mock
}

type mockConstructorTestingTNewStorageService interface {
	mock.TestingT
	Cleanup(func())
}

// NewStorageService creates a new instance of StorageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStorageService(t mockConstructorTestingTNewStorageService) *StorageService {
	mock := &StorageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
